title: The Missing SENG
description: A collection of notes and resources for the missing SENG courses at the University of Victoria.
theme: just-the-docs

url: https://keshvadi.github.io/themissingseng/

aux_links:
  The Missing SENG: https://keshvadi.github.io/themissingseng/